services:
  - type: web
    name: flask-investment-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: investment-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # You will set this manually in the Render dashboard

databases:
  - name: investment-db
    plan: free
    region: oregon
